# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcGene <- function(s_data, seqAll, prodValue, thresholds) {
    .Call('Biocomb_CalcGene', PACKAGE = 'Biocomb', s_data, seqAll, prodValue, thresholds)
}

CalcROC <- function(s_data, seq, thresholds) {
    .Call('Biocomb_CalcROC', PACKAGE = 'Biocomb', s_data, seq, thresholds)
}

